### ISSUE TITLE
Brainstorm a (potential) new name.

### ISSUE THREAD

**Issue by shymega** [shymega/scrobblers#7]
I'm not fully sold on the name for this project so far, and I'd like to explore/brainstorm potential new names.

In particular, the `.rs` suffix bothers me, and I'm also concerned about potential trouble from having the substring `scrobble` in the name..

**Comment by rubdos** [comment]
"scrobblers", as in, "two who scrobble" ? 

What's the concern with the term "scrobble"? Scares from last.fm?

**Comment by shymega** [comment]
I'm not sure about 'two who scrobble' - what's the reasoning behind that? My interpretation is 'one source, one target' -> i.e: two.

The concern I have with the term *is* Last.fm.. I suppose I could cross that bridge when it comes to it, but OTOH, it would be better to nip it in the bud.

**Comment by rubdos** [comment]
> I'm not sure about 'two who scrobble' - what's the reasoning behind that? My interpretation is 'one source, one target' -> i.e: two.

typo, "those who scrobble".

> The concern I have with the term is Last.fm.. I suppose I could cross that bridge when it comes to it, but OTOH, it would be better to nip it in the bud.

Has this ever been a problem for *any* project? If not, you can just claim that last.fm does nothing about protecting their trademark, given they even have one. On top of that, way larger projects than this one use `scrobble' in some form, and never had issues (afaik).

**Comment by shymega** [comment]
I've settled on Scrobblers right now. Rename in progress, please expect more commits in the future pertraining to this process.

Thanks for the help on this issue :cat:
